[database]
engine = "mariadb+mysqlconnector"
name = "central"
user = "central"
password = "central"
host = "host.docker.internal"
port = 3306
pool_size = 10
overflow = 5
pool_recycle = 3600
pool_pre_ping = true
echo = false

[redis]
connection_string = "redis://default:user@hostname:6379"
channel = "central"

[oauth]
client_secret = "12345678"
client_id = 12345678
endpoint_url = "http://127.0.0.1:8000/v1/oauth"

discord_server_id = "12345678"
discord_server_invite = "https://discord.com/invite/12345678"

[general]
# These values are provided by pyproject.toml and can be overridden here.
project_name = "FurFur Central"
project_desc = "API для объеденения множества серверов SS13 и SS14 в одну систему."
project_ver = "0.1.0"
favicon_path = "app/assets/favicon.png"
discord_webhook = "https://discord.com/api/webhooks/12345678/12345678"
